### ISSUE TITLE
Is there boxes label for car detection?

### ISSUE THREAD

**Issue by lhcalibur** [ZendarInc/ZendarSDK#26]
Hi, 
I want to know if there exist 3D boxes and center label for car detection(or 2d boxes label).
I can only find position label for radar detection, but can't find hwl, thanks!

**Comment by plb9772** [comment]
Hi,
There is currently no 3D boxes and center label for car detection in the dataset we released. We have plans to do so, but we cannot promise when it will be released.
Best,
Pierre-Louis
